#!/usr/bin/with-contenv bash

# copy config
[[ ! -f /config/config.yml ]] && cp \
	/defaults/config.yml /config/config.yml

if [ ! -z "$RSS" ] && [ ! -z "$USER" ] && [ ! -z "$PASS" ]; then
	sed -i "/rss/c\ \ \ \ rss: $RSS" /config/config.yml
	sed -i "/username/c\ \ \ \ \ \ \ \ username: $USER" /config/config.yml
	sed -i "/password/c\ \ \ \ \ \ \ \ password: $PASS" /config/config.yml
fi

# permissions
chown abc:abc \
	config.yml
